[tool.bandit]
exclude_dirs = ["tests"]

[project]
name = "time-addressable-media-store"
version = "0.0.0"
readme = "README.md"
requires-python = ">=3.14,<4.0.0"
dependencies = []

[dependency-groups]
dev = [
    "requests>=2.34.2",
    "pytest>=9.1.1",
    "boto3>=1.43.79",
    "pyaml>=26.7.0",
    "aws-lambda-powertools>=3.34.0",
    "pydantic>=2.13.4",
    "aws-xray-sdk>=2.15.0",
    "undecorated>=0.3.0",
    "deepdiff>=9.1.0",
    "mediatimestamp>=5.2.0",
    "cymple>=0.12.0",
    "moto>=5.2.3",
    "datamodel-code-generator>=0.75.1",
    "pytest-lazy-fixtures>=1.4.1",
    "pyjwt>=2.13.0",
    "responses>=0.26.2",
    "pylint>=4.0.7",
    "bandit>=1.7.0",
    "ruff>=0.16.4",
]
