query_params = {
    "/sources": {
        "HEAD": {
            "label": "str",
            "tag.{name}": "str",
            "tag_exists.{name}": "bool",
            "page": "str",
            "limit": "int",
        },
        "GET": {
            "label": "str",
            "tag.{name}": "str",
            "tag_exists.{name}": "bool",
            "format": "str",
            "page": "str",
            "limit": "int",
        },
    },
    "/flows": {
        "HEAD": {
            "source_id": "str",
            "timerange": "str",
            "format": "str",
            "codec": "str",
            "label": "str",
            "tag.{name}": "str",
            "tag_exists.{name}": "bool",
            "frame_width": "int",
            "frame_height": "int",
            "page": "str",
            "limit": "int",
        },
        "GET": {
            "source_id": "str",
            "timerange": "str",
            "format": "str",
            "codec": "str",
            "label": "str",
            "tag.{name}": "str",
            "tag_exists.{name}": "bool",
            "frame_width": "int",
            "frame_height": "int",
            "page": "str",
            "limit": "int",
        },
    },
    "/flows/{flowId}": {
        "HEAD": {"include_timerange": "bool", "timerange": "str"},
        "GET": {"include_timerange": "bool", "timerange": "str"},
    },
    "/flows/{flowId}/segments": {
        "HEAD": {
            "object_id": "str",
            "timerange": "str",
            "reverse_order": "bool",
            "accept_get_urls": "str",
            "page": "str",
            "limit": "int",
        },
        "GET": {
            "object_id": "str",
            "timerange": "str",
            "reverse_order": "bool",
            "accept_get_urls": "str",
            "page": "str",
            "limit": "int",
        },
        "DELETE": {"timerange": "str", "object_id": "str"},
    },
}

essence_params = {
    "sample_rate": "int",
    "channels": "int",
    "bit_depth": "int",
    "codec_parameters": "dict",
    "unc_parameters": "dict",
    "data_type": "str",
    "frame_rate": "dict",
    "frame_width": "int",
    "frame_height": "int",
    "interlace_mode": "str",
    "colorspace": "str",
    "transfer_characteristic": "str",
    "aspect_ratio": "dict",
    "pixel_aspect_ratio": "dict",
    "component_type": "str",
    "horiz_chroma_subs": "int",
    "vert_chroma_subs": "int",
    "avc_parameters": "dict",
}
