essence_params = {
    "sample_rate": "int",
    "channels": "int",
    "bit_depth": "int",
    "codec_parameters": "dict",
    "unc_parameters": "dict",
    "data_type": "str",
    "frame_rate": "dict",
    "frame_width": "int",
    "frame_height": "int",
    "interlace_mode": "str",
    "colorspace": "str",
    "transfer_characteristic": "str",
    "aspect_ratio": "dict",
    "pixel_aspect_ratio": "dict",
    "component_type": "str",
    "horiz_chroma_subs": "int",
    "vert_chroma_subs": "int",
    "avc_parameters": "dict",
}
