AWSTemplateFormatVersion: "2010-09-09"

Description: TAMS API Neptune Stack

Parameters:

  VpcId:
    Description: Neptune VPC ID
    Type: String

  VpcAZs:
    Description: Neptune AZs
    Type: List<AWS::EC2::AvailabilityZone::Name>

  PrivateSubnetIds:
    Description: Neptune VPC Private Subnets
    Type: List<AWS::EC2::Subnet::Id>

  LambdaSecurityGroupId:
    Description: Lambda Security Group ID
    Type: AWS::EC2::SecurityGroup::Id

Resources:

  DBSubnetGroup:
    Type: AWS::Neptune::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: TAMS Neptune DB Subnet Group
      SubnetIds: !Ref PrivateSubnetIds

  NeptuneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Neptune Lambdas
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - Description: Allow Lambda access to Neptune
          SourceSecurityGroupId: !Ref LambdaSecurityGroupId
          IpProtocol: tcp
          ToPort: 8182
          FromPort: 8182
      SecurityGroupEgress:
        - Description: No outbound access
          CidrIp: 0.0.0.0/32
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443

  TAMSNeptuneCluster:
    Type: AWS::Neptune::DBCluster
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F30
            reason: Storage Encryption not required
    Properties:
      AvailabilityZones: !Ref VpcAZs
      DBSubnetGroupName: !Ref DBSubnetGroup
      EngineVersion: 1.3.4.0
      VpcSecurityGroupIds:
        - !Ref NeptuneSecurityGroup
      ServerlessScalingConfiguration:
        MinCapacity: 1
        MaxCapacity: 128

  TAMSNeptuneInstance:
    Type: AWS::Neptune::DBInstance
    Properties:
      DBInstanceClass: db.serverless
      DBClusterIdentifier: !Ref TAMSNeptuneCluster

Outputs:

  ClusterResourceId:
    Value: !GetAtt TAMSNeptuneCluster.ClusterResourceId

  Endpoint:
    Value: !GetAtt TAMSNeptuneCluster.Endpoint
