AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  WebhooksTableName:
    Type: String

  OldStorageTableName:
    Type: String

  NewStorageTableName:
    Type: String

  NeptuneEndpoint:
    Type: String

  NeptuneClusterResourceId:
    Type: String

  PrivateSubnetIds:
    Type: CommaDelimitedList

  LambdaSecurityGroup:
    Type: String

  UtilsLayerArn:
    Type: String

Transform: AWS::Serverless-2016-10-31

Resources:
  NeptuneImportFunction:
    Type: AWS::Serverless::Function
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W89
            reason: Vpc defined in Globals section
          - id: W92
            reason: ReservedConcurrentExecutions not required
    Properties:
      Timeout: 900
      MemorySize: 10240
      Handler: index.lambda_handler
      Runtime: python3.13
      Architectures:
        - arm64
      Environment:
        Variables:
          POWERTOOLS_LOG_LEVEL: INFO
          WEBHOOKS_TABLE: !Ref WebhooksTableName
          OLD_STORAGE_TABLE: !Ref OldStorageTableName
          NEW_STORAGE_TABLE: !Ref NewStorageTableName
          NEPTUNE_ENDPOINT: !Ref NeptuneEndpoint
      Layers:
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV3-python313-arm64:18
        - !Ref UtilsLayerArn
      VpcConfig:
        SubnetIds: !Ref PrivateSubnetIds
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Scan
              Resource:
                - !Sub arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${WebhooksTableName}
                - !Sub arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${OldStorageTableName}
            - Effect: Allow
              Action:
                - dynamodb:BatchWriteItem
              Resource:
                - !Sub arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${NewStorageTableName}
            - Effect: Allow
              Action:
                - neptune-db:ReadDataViaQuery
                - neptune-db:WriteDataViaQuery
                - neptune-db:DeleteDataViaQuery
              Resource: !Sub arn:${AWS::Partition}:neptune-db:${AWS::Region}:${AWS::AccountId}:${NeptuneClusterResourceId}/*
              Condition:
                StringEquals:
                  neptune-db:QueryLanguage: OpenCypher
      InlineCode: |
        import os
        import uuid
        import boto3
        from neptune import merge_webhook

        dynamodb = boto3.resource("dynamodb")
        webhooks_table = dynamodb.Table(os.environ["WEBHOOKS_TABLE"])
        old_storage_table = dynamodb.Table(os.environ["OLD_STORAGE_TABLE"])
        new_storage_table = dynamodb.Table(os.environ["NEW_STORAGE_TABLE"])


        def webhooks_etl():
            scan = webhooks_table.scan()
            items = scan["Items"]
            while "LastEvaluatedKey" in scan:
                scan = webhooks_table.scan(ExclusiveStartKey=scan["LastEvaluatedKey"])
                items.extend(scan["Items"])
            webhooks_dict = {}
            for item in items:
                event = item.pop("event")
                if item["url"] in webhooks_dict:
                    webhooks_dict[item["url"]]["events"].append(event)
                else:
                    webhooks_dict[item["url"]] = {**item, "events": [event]}
            for webhook_dict in webhooks_dict.values():
                webhook_dict["id"] = str(uuid.uuid4())
                webhook_dict["status"] = "created"
                merge_webhook(webhook_dict, None)


        def storage_etl():
            with new_storage_table.batch_writer() as batch:
                scan = old_storage_table.scan()
                for item in scan["Items"]:
                    batch.put_item(Item=item)
                while "LastEvaluatedKey" in scan:
                    scan = old_storage_table.scan(ExclusiveStartKey=scan["LastEvaluatedKey"])
                    for item in scan["Items"]:
                        batch.put_item(Item=item)


        def lambda_handler(event, context):
            webhooks_etl()
            storage_etl()
